default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['DB_HOST'] || 'db' %>
  password: <%= ENV['DB_PASSWORD'] || 'abc123' %>
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  database: rentpay_<%= ENV['RAILS_ENV'] || 'test' %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
